export const APPOINTMENT_CREATION_REQUEST = 'APPOINTMENT_CREATION_REQUEST';
export const APPOINTMENT_CREATION_SUCCESS = 'APPOINTMENT_CREATION_SUCCESS';
export const APPOINTMENT_CREATION_FAIL = 'APPOINTMENT_CREATION_FAIL';
