export const LIST_APPOINTMENTS_REQUEST = 'LIST_APPOINTMENTS_REQUEST';
export const LIST_APPOINTMENTS_SUCCESS = 'LIST_APPOINTMENTS_SUCCESS';
export const LIST_APPOINTMENTS_FAIL = 'LIST_APPOINTMENTS_FAIL';

export const APPOINTMENT_DECISION_REQUEST = 'APPOINTMENT_DECISION_REQUEST';
export const APPOINTMENT_DECISION_SUCCESS = 'APPOINTMENT_DECISION_SUCCESS';
export const APPOINTMENT_DECISION_FAIL = 'APPOINTMENT_DECISION_FAIL';
