export const SLOTS_LIST_REQUEST = 'SLOTS_LIST_REQUEST';
export const SLOTS_LIST_SUCCESS = 'SLOTS_LIST_SUCCESS';
export const SLOTS_LIST_FAIL = 'SLOTS_LIST_FAIL';

export const SLOT_DELETION_REQUEST = 'SLOT_DELETION_REQUEST';
export const SLOT_DELETION_SUCCESS = 'SLOT_DELETION_SUCCESS';
export const SLOT_DELETION_FAIL = 'SLOT_DELETION_FAIL';

export const SLOT_CREATION_REQUEST = 'SLOT_CREATION_REQUEST';
export const SLOT_CREATION_SUCCESS = 'SLOT_CREATION_SUCCESS';
export const SLOT_CREATION_FAIL = 'SLOT_CREATION_FAIL';
